// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWdPBOYKnNYktkzPz7p9NTafcrwgov5YY',
    appId: '1:817229853297:web:7fd82bded8999e76aba1d0',
    messagingSenderId: '817229853297',
    projectId: 'chat-app-4e30c',
    authDomain: 'chat-app-4e30c.firebaseapp.com',
    storageBucket: 'chat-app-4e30c.appspot.com',
    measurementId: 'G-G9EK3FBY0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA40aKnUgjDIMnSQUv6p2tcd__XkMLVSXY',
    appId: '1:817229853297:android:7b18f6a731f2b968aba1d0',
    messagingSenderId: '817229853297',
    projectId: 'chat-app-4e30c',
    storageBucket: 'chat-app-4e30c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr4vVf_qES0RQHgE-jUqCCrNG3YfR1EAE',
    appId: '1:817229853297:ios:2d45a3fb52e5c684aba1d0',
    messagingSenderId: '817229853297',
    projectId: 'chat-app-4e30c',
    storageBucket: 'chat-app-4e30c.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr4vVf_qES0RQHgE-jUqCCrNG3YfR1EAE',
    appId: '1:817229853297:ios:2d45a3fb52e5c684aba1d0',
    messagingSenderId: '817229853297',
    projectId: 'chat-app-4e30c',
    storageBucket: 'chat-app-4e30c.appspot.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
